// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp_0iawUiVcYUO4k8VkD-pCYGNY2mZtFY',
    appId: '1:548228108837:web:7bc4ebaa58d68380b265cc',
    messagingSenderId: '548228108837',
    projectId: 'aiia-chatapp',
    authDomain: 'aiia-chatapp.firebaseapp.com',
    storageBucket: 'aiia-chatapp.appspot.com',
    measurementId: 'G-JW0B8V96JN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS_KrtqcutqNxKw-M8viGCocEnXERBLqw',
    appId: '1:548228108837:android:9441dbe93070a9f6b265cc',
    messagingSenderId: '548228108837',
    projectId: 'aiia-chatapp',
    storageBucket: 'aiia-chatapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvZD8NK2wkCSTXhzH4_pFYdynywSFwPY8',
    appId: '1:548228108837:ios:f381d8a7a73533b0b265cc',
    messagingSenderId: '548228108837',
    projectId: 'aiia-chatapp',
    storageBucket: 'aiia-chatapp.appspot.com',
    iosClientId: '548228108837-np280i1rv6en8bqn783kfuonhra92i52.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvZD8NK2wkCSTXhzH4_pFYdynywSFwPY8',
    appId: '1:548228108837:ios:f381d8a7a73533b0b265cc',
    messagingSenderId: '548228108837',
    projectId: 'aiia-chatapp',
    storageBucket: 'aiia-chatapp.appspot.com',
    iosClientId: '548228108837-np280i1rv6en8bqn783kfuonhra92i52.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiia',
  );
}
